name: droomy
description: "Make your dream job a reality."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  google_sign_in: ^6.2.1
  riverpod: ^2.4.9
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  json_annotation: ^4.8.1
  cloud_firestore: ^4.13.6
  json_theme: ^6.4.0

  # TODO: Change implementation to avoid using alpha package
  flutter_html: ^3.0.0-alpha.3
  freezed_annotation: ^2.4.1
  flutter_signin_button: ^2.0.0
  shimmer_animation: ^2.1.0+1
  audioplayers: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6

flutter:
  uses-material-design: true

  assets:
    - assets/light_theme.json
    - assets/dark_theme.json
    - assets/cow.png
    - assets/sounds/sfx_step_completed_success.mp3
    - assets/sounds/sfx_task_done_bleep.mp3
    - assets/sounds/sfx_undo_woosh.mp3

  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand/Quicksand-Bold.ttf
        - asset: fonts/Quicksand/Quicksand-Light.ttf
        - asset: fonts/Quicksand/Quicksand-Medium.ttf
        - asset: fonts/Quicksand/Quicksand-Regular.ttf
        - asset: fonts/Quicksand/Quicksand-SemiBold.ttf